# Generated by Django 5.1.3 on 2025-01-21 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
                ('requester', models.CharField(max_length=100)),
                ('prefecture', models.CharField(max_length=100)),
                ('reward', models.CharField(default=1, max_length=3)),
                ('payment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('answer_photo', models.ImageField(upload_to='quest_photos/')),
                ('additional_notes', models.TextField()),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('quest_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quest_registers', to='formapp.quest', verbose_name='クエストID')),
            ],
        ),
    ]
